name: Docker CI/CD

# Roda quando damos push na main
on:
  push:
    branches: [ "main" ]

# Variáveis de ambiente
env:
  REGISTRY: ghcr.io
  # O nome da imagem será: ghcr.io/seu-usuario/git-lab-02
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Permissões necessárias para gravar no registro de pacotes do GitHub
    permissions:
      contents: read
      packages: write

    steps:
      - name: Baixar o código (Checkout)
        uses: actions/checkout@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest